site_name: Analyzing SAXS data
site_description: Analyzing SAXS data
site_author: Normand Cyr

site_url: http://airen.bcm.umontreal.ca/biostruct/SAXS_tutorials/
repo_url: https://github.com/normcyr

theme:
  name: cinder
  custom_dir: custom_theme/

nav:
  - Instrumentation: instrumentation.md
  - Running a SAXS experiment: saxs_experiment.md
  - Basic processing: basic_data_processing.md
  - Advanced processing: advanced_data_processing.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
  - fenced_code
  - meta
