site_name: Analyzing SAXS data
site_description: Analyzing SAXS data
site_author: Normand Cyr

site_url: http://airen.bcm.umontreal.ca/biostruct/SAXS_tutorials/
repo_url: https://github.com/BioStruct-UdeM/SAXS_tutorials

theme:
  name: cinder
  custom_dir: custom_theme/

nav:
  - Instrumentation:
    - Overview: overview_instrumentation.md
    - Software: details_instrument_software.md
    - Maintenance: maintenance.md
  - Running a SAXS experiment:
    - Basic SAXS: saxs_experiment.md
    - SEC-SAXS: sec-saxs_setup.md
  - Data processing:
    - Basic data processing: basic_data_processing.md
    - Advanced processing: advanced_data_processing.md
    - SEC-SAXS data processing: sec-saxs.md
  - Ab initio modeling:
    - DAMMIF: modeling_with_dammif.md
    - DENSS: modeling_with_denss.md

extra_css:
    - css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

dev_addr:
  127.0.0.1:8080

markdown_extensions:
  - mdx_math
  - fenced_code
  - meta
  - sane_lists
  - toc:
      toc_depth: 3

plugins:
  - search
  - bootstrap-tables
